theme: jekyll-theme-minimal
title: FHOÖ BIN Proteomics
description: GitHub Page of the Bioinformatics/Proteomics Research Group FH OÖ Campus Hagenberg
logo: https://raw.githubusercontent.com/hgb-bin-proteomics/hgb-bin-proteomics.github.io/master/docs/bin-logo.png
github:
  is_project_page: true
  is_user_page: false
show_downloads: true
